-- Add DEFAULT constraints back in

ALTER TABLE games
ALTER COLUMN id SET DEFAULT gen_random_uuid(),
ALTER COLUMN is_deleted SET DEFAULT FALSE, ALTER COLUMN is_deleted DROP NOT NULL,
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN created_at DROP NOT NULL,
ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE scores
ALTER COLUMN id SET DEFAULT gen_random_uuid(),
ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP, ALTER COLUMN created_at DROP NOT NULL,
ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN is_deleted SET DEFAULT FALSE, ALTER COLUMN is_deleted DROP NOT NULL;
