-- CREATE TABLE scores

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS scores (
    id uuid DEFAULT uuid_generate_v4(),
    game uuid REFERENCES games (id),
    initials VARCHAR(3) NOT NULL,
    score VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

