-- Drop DEFAULT constraints to favor manual insertion

ALTER TABLE games
ALTER COLUMN id DROP DEFAULT,
ALTER COLUMN is_deleted DROP DEFAULT, ALTER COLUMN is_deleted SET NOT NULL,
ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN created_at SET NOT NULL,
ALTER COLUMN updated_at DROP DEFAULT;

ALTER TABLE scores
ALTER COLUMN id DROP DEFAULT,
ALTER COLUMN created_at DROP DEFAULT, ALTER COLUMN created_at SET NOT NULL,
ALTER COLUMN updated_at DROP DEFAULT,
ALTER COLUMN is_deleted DROP DEFAULT, ALTER COLUMN is_deleted SET NOT NULL;
