### Display games
GET http://localhost:7000/games


### Display single game
GET http://localhost:7000/games/eae79bac-0a26-47f6-aff3-9e4d072186de


### Add game
POST http://localhost:7000/games
Content-Type: application/json

{
    "title": "New game",
    "description": "This should not be added!"
}


### Update game
PUT http://localhost:7000/games/eae79bac-0a26-47f6-aff3-9e4d072186de
Content-Type: application/json

{
    "title": "Ninja Gaiden",
    "description": "A classic"
}


### Delete game
DELETE http://localhost:7000/games/eae79bac-0a26-47f6-aff3-9e4d072186de


##############
### SCORES ###
##############


### Display scores
GET http://localhost:7000/scores


### Display single score
GET http://localhost:7000/scores/95e25db0-9057-42f7-bb87-03d6335f65c2


### Add score
POST http://localhost:7000/scores
Content-Type: application/json

{
    "game": "eae79bac-0a26-47f6-aff3-9e4d072186de",
    "initials": "DRJ",
    "score": 100029020
}


### Delete score
DELETE http://localhost:7000/scores/eae79bac-0a26-47f6-aff3-9e4d072186de


### Update score
PUT http://localhost:7000/scores/8119e6fc-d3d7-41e1-a57a-ebe4379a216c
Content-Type: application/json

{
    "initials": "DRJ",
    "score": 1000010,
    "game": "eae79bac-0a26-47f6-aff3-9e4d072186de"
}
