### Display games
GET http://localhost:7000/games


### Display single game
GET http://localhost:7000/games/3d907a0e-8793-4061-b170-353f885e6e10


### Add game
POST http://localhost:7000/games
Content-Type: application/json

{
    "id": "48b260ee-9471-4de6-9dd4-652d4534fe06",
    "title": "ANOTHER NEW GAME"
}


### Update game
PUT http://localhost:7000/games/48b260ee-9471-4de6-9dd4-652d4534fe02
Content-Type: application/json

{
    "title": "Work now!",
    "description": "New description"
}


### Delete game
DELETE http://localhost:7000/games/48b260ee-9471-4de6-9dd4-652d4534fe02


##############
### SCORES ###
##############


### Display scores
GET http://localhost:7000/scores


### Display single score
GET http://localhost:7000/scores/98b72df5-d470-45c5-a011-02444e159a07


### Add score
POST http://localhost:7000/scores
Content-Type: application/json

{
    "game": "e00a250f-8155-47b8-bf8b-61dc193784d0",
    "initials": "DRJ",
    "score": 3393932
}


### Delete score
DELETE http://localhost:7000/scores/98b72df5-d470-45c5-a011-02444e159a07


### Update score
PUT http://localhost:7000/scores/98b72df5-d470-45c5-a011-02444e159a07
Content-Type: application/json

{
    "initials": "CCC",
    "score": "335"
}
