### Display games
GET http://localhost:7000/games


### Display single game
GET http://localhost:7000/games/528e26f5-df0f-4255-a5e8-acf0fddddad0


### Add game
POST http://localhost:7000/games
Content-Type: application/json

{
    "title": "New game",
    "description": "This should not be added!"
}


### Update game
PUT http://localhost:7000/games/528e26f5-df0f-4255-a5e8-acf0fddddad0
Content-Type: application/json

{
    "title": "Updated GAMEEEEE",
    "description": "We just updated a game"
}


### Delete game
DELETE http://localhost:7000/games/528e26f5-df0f-4255-a5e8-acf0fddddad0


##############
### SCORES ###
##############


### Display scores
GET http://localhost:7000/scores


### Display single score
GET http://localhost:7000/scores/2


### Add score
POST http://localhost:7000/scores
Content-Type: application/json

{
    "initials": "GLC",
    "score": 8893201,
    "game": "Frogger"
}


### Delete score
DELETE http://localhost:7000/scores/3


### Update score
PUT http://localhost:7000/scores/2
Content-Type: application/json

{
    "initials": "GLC",
    "score": 7543298,
    "game": "Attack From Mars updated"
}
